
x-base-litellm: &base_litellm
    build:
      context: ./litellm
      dockerfile: Dockerfile
    ports:
      - "8000:4000"
    restart: unless-stopped
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api
      - MODEL=$MODEL

x-base-ollama: &base_ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    restart: unless-stopped
    networks:
      default:
        aliases:
          - ollama

x-base-open-webui: &base_open_webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    pull_policy: always
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped

services:
  litellm-gpu:
    <<: *base_litellm    
    profiles:
      - gpu
    depends_on:
      - ollama-gpu

  litellm-cpu:
    <<: *base_litellm
    profiles:
      - cpu
    depends_on:
      - ollama-cpu

  ollama-gpu:
    <<: *base_ollama
    profiles:
      - gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-cpu:
    <<: *base_ollama
    profiles:
      - cpu

  open-webui-gpu:
    <<: *base_open_webui
    profiles:
      - gpu
    depends_on:
      - ollama-gpu

  open-webui-cpu:
    <<: *base_open_webui
    profiles:
      - cpu
    depends_on:
      - ollama-cpu

volumes:
  ollama: {}
  open-webui: {}
